Repository hmcts/idam-user-dashboard, pull requests merged in 2021-12, with the labels that each got.

#43 Removed use of docker for running Playwright tests
  package.json
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-43

#69 SIDM-6753 Display cross browser test reports correctly on Jenkins nightly build dashboard
  Dockerfile
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  docker-compose.yml
  package.json
  src/test/cross-browser/runCrossBrowserTests.sh
  src/test/cross-browser/supportedBrowsers.js
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-69

#73 Removed unused SSL resources
  src/main/resources/localhost-ssl/README.md
  src/main/resources/localhost-ssl/localhost.crt
  src/main/resources/localhost-ssl/localhost.key
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-73

#70 Pa11y
  Jenkinsfile_CNP
  jest.a11y.config.js
  package.json
  src/test/a11y/a11y.ts
  src/test/a11y/dummy-test.ts
  src/test/tsconfig.json
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-70

#71 SIDM-6768 Read secrets from key vaults to be used in user dashboard config
  config/default.yaml
  src/main/modules/properties-volume/index.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-71

#80 Updated to use npm-run-all rather && for chaining commands
  package.json
  src/test/cross-browser/runCrossBrowserTests.sh
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-80

#81 SIDM-6804 Add manage users capability to IDAM user dashboard
  config/default.yaml
  jest.config.js
  package.json
  src/main/Api.ts
  src/main/app.ts
  src/main/controllers/AddUsersController.ts
  src/main/controllers/ManageUsersController.ts
  src/main/controllers/UserOptionController.ts
  src/main/controllers/UserResultsController.ts
  src/main/interfaces/PageData.ts
  src/main/interfaces/User.ts
  src/main/interfaces/UserResultData.ts
  src/main/modules/awilix/index.ts
  src/main/modules/helmet/index.ts
  src/main/modules/oidc/index.ts
  src/main/routes.ts
  src/main/server.ts
  src/main/utils/error.ts
  src/main/utils/utils.ts
  src/main/utils/validation.ts
  src/main/views/add-users.njk
  src/main/views/logout.njk
  src/main/views/manage-users.njk
  src/main/views/template.njk
  src/main/views/user-details.njk
  src/main/views/user-option.njk
  src/test/unit/test/Api.ts
  src/test/unit/test/controllers/AddUsersController.ts
  src/test/unit/test/controllers/ManageUsersController.ts
  src/test/unit/test/controllers/UserOptionController.ts
  src/test/unit/test/controllers/UserResultsController.ts
  src/test/unit/test/utils/utils.ts
  src/test/unit/test/utils/validation.ts
  src/test/unit/utils/mockRequest.ts
  src/test/unit/utils/mockResponse.ts
  src/test/unit/utils/utils.ts
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-81

#88 SIDM-6836 Pull smoke test username and password from Azure key vaults in Jenkins for tests
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-88

#85 Fix 'Too many redirects' issue for slow IDAM login
  src/main/modules/oidc/index.ts
  src/main/views/redirect.njk
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-85
