Repository hmcts/idam-user-dashboard, pull requests merged in 2022-01, with the labels that each got.

#91 idam-config - Configured idam-pr dependency and environment specific …
  .gitignore
  Jenkinsfile_CNP
  charts/idam-user-dashboard/Chart.yaml
  charts/idam-user-dashboard/values.aat.template.yaml
  charts/idam-user-dashboard/values.preview.template.yaml
  charts/idam-user-dashboard/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-91

#94 SIDM-6837 - Login / Logout fixes
  config/custom-environment-variables.yaml
  config/default.yaml
  sonar-project.properties
  src/main/Api.ts
  src/main/HttpError.ts
  src/main/app.ts
  src/main/controllers/UserOptionController.ts
  src/main/interfaces/Logger.ts
  src/main/modules/csrf/index.ts
  src/main/modules/error-handler/index.ts
  src/main/modules/oidc/index.ts
  src/main/modules/properties-volume/index.ts
  src/main/modules/session/index.ts
  src/main/routes.ts
  src/main/utils/error.ts
  src/main/utils/urls.ts
  src/main/utils/validation.ts
  src/main/views/error.njk
  src/main/views/home.njk
  src/main/views/macros/csrf.njk
  src/main/views/manage-users.njk
  src/main/views/not-found.njk
  src/main/views/redirect.njk
  src/main/views/template.njk
  src/main/views/user-option.njk
  src/test/unit/test/Api.ts
  src/test/unit/test/controllers/UserOptionController.ts
  src/test/unit/test/controllers/UserResultsController.ts
  src/test/unit/test/utils/validation.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-94

#98 CVE-2022-0155 patch
  package.json
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-98

#97 Fix for nightly builds due to PARAMS.ENVIROMENT not existing
  Jenkinsfile_nightly
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-97

#99 Fix access token not set when calling IDAM API
  src/main/modules/oidc/index.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-99

#100 Add IDAM_SYSTEM_OWNER to default role for sorting in the user results screen
  src/main/utils/utils.ts
  src/test/unit/test/utils/utils.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-100

#101 Sidm 6802
  package.json
  src/test/config.ts
  src/test/functional/codecept.conf.ts
  src/test/functional/custom-steps.ts
  src/test/functional/manage-users-test.ts
  src/test/functional/shared/idam-helper.ts
  src/test/functional/shared/random-data.ts
  src/test/functional/steps.d.ts
  src/test/functional/steps_file.js
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-101

#103 SIDM-6753 - Added TEST_URL variable to nightly build
  Jenkinsfile_nightly
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-103

#106 Update values.yaml
  charts/idam-user-dashboard/Chart.yaml
  charts/idam-user-dashboard/values.aat.template.yaml
  charts/idam-user-dashboard/values.yaml
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-106

#104 Search-use functional test initial commit
  src/main/views/user-details.njk
  src/test/functional/custom-steps.ts
  src/test/functional/manage-users-test.ts
  src/test/functional/search-user-test.ts
  src/test/functional/steps.d.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-104

#107 Updated idam-session cookie to idam-user-dashboard-session
  src/main/modules/session/index.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-107

#108 enable_redis - Added redis cache hostname, port and pass
  charts/idam-user-dashboard/Chart.yaml
  charts/idam-user-dashboard/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/modules/health/index.ts
  src/main/modules/properties-volume/index.ts
  src/main/modules/session/index.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-108

#110 CVE-2022-0235 - Updated node-fetch dependency
  package.json
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-110

#113 CVE-2022-0144 / CVE-2020-28499 / CVE-2021-23807 - Removed sass-lint
  .sass-lint.yml
  package.json
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-113

#117 Improved health-check smoke test
  src/test/smoke/smoke.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-117

#115 SIDM-6753
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  package.json
  src/test/cross-browser/runCrossBrowserTests.sh
  src/test/cross-browser/saucelabs.conf.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-115
