Repository hmcts/idam-user-dashboard, pull requests merged in 2023-12, with the labels that each got.

#759 Do not lose telemetry for sign-ins
  src/main/modules/appinsights/index.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-759

#760 SIDM-8920 fix audit issue
  audit.json
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-760

#762 Suppress 10096_Timestamp_Disclosure
  audit.json
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-762
