Repository hmcts/idam-user-dashboard, pull requests merged in 2023-03, with the labels that each got.

#447 Sidm 8453 test fix
  src/test/config.ts
  src/test/cross-browser/saucelabs.conf.ts
  src/test/tsconfig.json
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-447

#440 SIDM-8447 - Updated invite user to use V2 endpoints
  config/default.yaml
  src/main/app/authorized-axios/AuthorizedAxios.ts
  src/main/app/invite-service/Invite.ts
  src/main/app/invite-service/InviteService.ts
  src/main/app/service-provider-service/ServiceProvider.ts
  src/main/app/service-provider-service/ServiceProviderService.ts
  src/main/controllers/AddPrivateBetaServiceController.ts
  src/main/controllers/AddUserRolesController.ts
  src/main/interfaces/Service.ts
  src/main/modules/awilix/index.ts
  src/main/views/add-user-roles.njk
  src/test/functional/register-user-test.ts
  src/test/unit/test/app/invite-service/InviteService.ts
  src/test/unit/test/app/service-provider-service/ServiceProviderService.ts
  src/test/unit/test/controllers/AddPrivateBetaServiceController.ts
  src/test/unit/test/controllers/AddUserRolesController.ts
  src/test/unit/test/utils/serviceUtils.ts
  src/test/unit/utils/mockAxios.ts
  src/test/unit/utils/mockInviteService.ts
  src/test/unit/utils/mockLogger.ts
  src/test/unit/utils/mockServiceProviderService.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-440

#450 SIDM-8518 Ignore the issue as no fix released
  yarn-audit-known-issues
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-450

#436 SIDM-8428 - Yarn 3 migration
  .dockerignore
  .gitignore
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarn/releases/yarn-3.4.1.cjs
  .yarnrc.yml
  Dockerfile
  package.json
  src/main/assets/scss/main.scss
  src/main/modules/awilix/index.ts
  webpack/govukFrontend.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-436

#460 Fix for crossbrowser test report not generating correctly
  package.json
  src/test/config.ts
  src/test/cross-browser/saucelabs.conf.ts
  src/test/functional/codecept.conf.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-460
