Repository hmcts/idam-user-dashboard, pull requests merged in 2023-11, with the labels that each got.

#665 SIDM-8456 Remove limit on reports
  .eslintrc.js
  package.json
  src/main/app/feature-flags/FeatureFlags.ts
  src/main/app/feature-flags/LaunchDarklyClient.ts
  src/main/app/idam-api/IdamAPI.ts
  src/main/app/reports/ReportsHandler.ts
  src/main/controllers/DownloadReportController.ts
  src/main/controllers/GenerateReportController.ts
  src/main/controllers/UserEditController.ts
  src/main/controllers/ViewReportController.ts
  src/main/modules/awilix/index.ts
  src/main/modules/error-handler/index.ts
  src/main/modules/oidc/index.ts
  src/main/routes.ts
  src/main/utils/urls.ts
  src/main/views/view-report.njk
  src/test/functional/shared/helpers/featureFlagHelper.ts
  src/test/functional/shared/helpers/testingSupportApiHelper.ts
  src/test/unit/test/app/idam-api/IdamAPI.ts
  src/test/unit/test/app/reports/ReportsHandler.ts
  src/test/unit/test/controllers/AddPrivateBetaServiceController.ts
  src/test/unit/test/controllers/AddUserDetailsController.ts
  src/test/unit/test/controllers/AddUserRolesController.ts
  src/test/unit/test/controllers/DownloadReportController.ts
  src/test/unit/test/controllers/GenerateReportController.ts
  src/test/unit/test/controllers/RootController.ts
  src/test/unit/test/controllers/UserEditController.ts
  src/test/unit/test/controllers/UserResultsController.ts
  src/test/unit/test/controllers/ViewReportController.ts
  src/test/unit/utils/mockRootController.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-665

#677 SIDM-8951 Tests on other environments
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  charts/idam-user-dashboard/Chart.yaml
  charts/idam-user-dashboard/values.yaml
  config/custom-environment-variables.yaml
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-677

#686 Improve and fix reports features
  src/main/controllers/DownloadReportController.ts
  src/main/modules/helmet/index.ts
  src/main/utils/error.ts
  src/main/views/generate-report.njk
  src/test/unit/test/controllers/DownloadReportController.ts
  yarn-audit-known-issues
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-686

#685 SIDM-8925 Add zap scanner
  Jenkinsfile_nightly
  audit.json
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-685

#691 Fix pally test issue
  src/main/controllers/DownloadReportController.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-691

#698 Update axios
  package.json
  src/main/app/authorized-axios/AuthorizedAxios.ts
  src/test/functional/edit-user-test.ts
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-698

#699 Fix crossbrowser nightly
  package.json
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-699

#558 Retries for emails
  src/test/functional/shared/testingSupportApi.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-558

#716 update app insights
  charts/idam-user-dashboard/Chart.yaml
  charts/idam-user-dashboard/values.preview.template.yaml
  charts/idam-user-dashboard/values.yaml
  config/default.yaml
  package.json
  src/main/modules/appinsights/index.ts
  src/main/modules/properties-volume/index.ts
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-716

#720 Update config.ts
  src/test/config.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-720

#721 SIDM-8984 Remove old teardown
  src/test/a11y/a11y.ts
  src/test/functional/codecept.conf.ts
  src/test/functional/generate-user-report-test.ts
  src/test/functional/manage-users-test.ts
  src/test/functional/shared/helpers/testingSupportApiHelper.ts
  src/test/functional/shared/testingSupportApi.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-721

#722 Clean up some code smells
  src/main/controllers/UserEditController.ts
  src/main/controllers/UserOptionController.ts
  src/main/controllers/UserResultsController.ts
  src/main/utils/roleUtils.ts
  src/main/utils/serviceUtils.ts
  src/main/utils/utils.ts
  src/test/functional/shared/testingSupportApi.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-722

#729 SIDM 8984 fixes
  package.json
  src/test/functional/shared/random-data.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-729

#730 SIDM-8984 retry login
  src/test/functional/delete-user-test.ts
  src/test/functional/edit-user-test.ts
  src/test/functional/error-page-test.ts
  src/test/functional/generate-user-report-test.ts
  src/test/functional/lock-account-test.ts
  src/test/functional/manage-users-test.ts
  src/test/functional/register-user-test.ts
  src/test/functional/remove-SSO-ID-test.ts
  src/test/functional/search-user-test.ts
  src/test/functional/sign-in-user-test.ts
  src/test/functional/suspend-user-test.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-730

#736 SIDM-8984 cross browser tests
  src/test/cross-browser/saucelabs.conf.ts
  src/test/functional/register-user-test.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-736

#738 SIDM-8984 check login worked
  src/test/functional/custom-steps.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-738

#717 Sync nightly-dev with master
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-717

#741 SIDM-8984 Change renovate schedule to afternoon
  .github/renovate.json
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-741
