Repository hmcts/idam-user-dashboard, pull requests merged in 2023-07, with the labels that each got.

#503 Update yarn-audit-known-issues
  yarn-audit-known-issues
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-503

#507 dependencies
  yarn-audit-known-issues
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-507

#508 config
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  package.json
  src/test/config.ts
  src/test/cross-browser/saucelabs.conf.ts
  src/test/functional/codecept.conf.ts
  src/test/functional/custom-steps.ts
  src/test/functional/edit-user-test.ts
  src/test/functional/sign-in-user-test.ts
  yarn-audit-known-issues
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-508

#511 update packages
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarnrc.yml
  package.json
  src/test/functional/custom-steps.ts
  src/test/functional/lock-account-test.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-511

#513 for pr
  src/main/modules/appinsights/index.ts
  src/main/modules/error-handler/index.ts
  src/main/modules/oidc/index.ts
  src/test/config.ts
  src/test/cross-browser/saucelabs.conf.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-513
