Repository hmcts/idam-user-dashboard, pull requests merged in 2024-01, with the labels that each got.

#773 Added pally tests and amended config
  package.json
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-773

#775 Revert "Added pally tests and amended config"
  package.json
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-775

#776 SIDM-9034 Renovate schedule
  .github/renovate.json
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-776

#781 updates
  package.json
  src/main/views/webpack/css.njk
  src/main/views/webpack/js.njk
  yarn-audit-known-issues
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-781

#797 Hide roles I cant assign
  src/main/modules/helmet/index.ts
  src/main/views/macros/roleList.njk
  src/test/functional/edit-user-test.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-797

#800 Sidm 9038 v2 codecept
  Jenkinsfile_CNP
  package-lock.json
  package.json
  src/test/v2/common/dao/SetupDao.ts
  src/test/v2/common/factories/users.ts
  src/test/v2/common/shared_config.ts
  src/test/v2/common/steps_file.ts
  src/test/v2/cross-browser/codecept.conf.js
  src/test/v2/cross-browser/saucelabs.conf.ts
  src/test/v2/functional/codecept.conf.js
  src/test/v2/functional/codecept.conf.ts
  src/test/v2/functional/steps.d.ts
  src/test/v2/functional/view_user_test.ts
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-800

#803 SIDM-9038 v2 test tweaks
  src/test/functional/manage-users-test.ts
  src/test/v2/common/steps_file.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-803

#818 add bootstrap delay
  src/test/v2/cross-browser/saucelabs.conf.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-818
