Repository hmcts/idam-user-dashboard, pull requests merged in 2024-03, with the labels that each got.

#857 SIDM-9020-Added Accessibility tests to idam-user-dashboard
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  jest.a11y.config.js
  package.json
  src/test/a11y/a11y.ts
  src/test/a11y/aggregateAccessibilityResults.js
  src/test/a11y/amendAccessibilityReport.js
  src/test/v2/accessibility/accessibility_test.ts
  src/test/v2/accessibility/codecept.conf.js
  src/test/v2/accessibility/codecept.conf.ts
  src/test/v2/common/shared_config.ts
  src/test/v2/common/steps_file.ts
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-857

#860 retry click
  src/test/v2/common/steps_file.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-860

#865 Upgrade jose to address CVE-2024-28176
  package.json
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-865

#866 SIDM-9139 Enable accessibility tests
  package.json
  src/main/views/macros/breadcrumb.njk
  src/main/views/template.njk
  src/test/v2/common/shared_config.ts
  src/test/v2/common/steps_file.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-866

#868 Try bump puppeteer
  package.json
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-868

#871 SIDM-8920 fix audit issue
  package.json
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-871
