Repository hmcts/idam-user-dashboard, pull requests merged in 2024-08, with the labels that each got.

#932 Update renovate.json
  .github/renovate.json
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-932

#934 Added dependency check suppressions.
  yarn-audit-known-issues
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-934

#935 Added audit suppressions to fix pipeline failures.
  package.json
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-935

#936 SIDM-9365 Java 21
  java/build.gradle
  java/gradle/wrapper/gradle-wrapper.jar
  java/gradle/wrapper/gradle-wrapper.properties
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-936

#937 SIDM-9354 remove redundant tokens from oidc middleware
  config/default.yaml
  src/main/app/idam-api/IdamAPI.ts
  src/main/controllers/AddPrivateBetaServiceController.ts
  src/main/controllers/AddUserDetailsController.ts
  src/main/controllers/AddUserRolesController.ts
  src/main/interfaces/Role.ts
  src/main/interfaces/V2Role.ts
  src/main/modules/oidc/index.ts
  src/main/utils/roleUtils.ts
  src/main/utils/serviceUtils.ts
  src/test/unit/test/app/idam-api/IdamAPI.ts
  src/test/unit/test/controllers/AddPrivateBetaServiceController.ts
  src/test/unit/test/controllers/AddUserDetailsController.ts
  src/test/unit/test/controllers/AddUserRolesController.ts
  src/test/unit/test/utils/roleUtils.ts
  src/test/unit/test/utils/serviceUtils.ts
  src/test/unit/utils/mockApi.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-937
