Repository hmcts/idam-user-dashboard, pull requests merged in 2024-05, with the labels that each got.

#884 Bump timeout value
  .nvmrc
  config/default.yaml
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-884

#885 Bump timeout
  package.json
  src/main/modules/health/index.ts
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-885

#893 wait after filtering roles
  src/test/v2/functional/edit_user_test.ts
  src/test/v2/functional/register_user_test.ts
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-893
