Repository hmcts/idam-user-dashboard, pull requests merged in 2024-06, with the labels that each got.

#897 SIDM-9225 fix
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-897

#898 Remove redundent IP package
  package.json
  src/main/views/webpack/css.njk
  src/main/views/webpack/js.njk
  yarn-audit-known-issues
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-898

#899 Move secret into lookup
  config/default.yaml
  package.json
  src/main/modules/properties-volume/index.ts
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-899

#900 Dependency check fixes.
  package.json
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-900

#901 Dependency check fixes.
  package.json
  yarn.lock
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-901

#903 Change "nightly" pipeline to run in the afternoon
  Jenkinsfile_nightly
Labels: ns:idam, prd:idam, rel:idam-user-dashboard-pr-903
